mysql:
  image: mariadb
  environment:
   MYSQL_ROOT_PASSWORD: 

phpmyadmin:
  image: corbinu/docker-phpmyadmin
  restart: always
  links:
   - mysql:mysql
  ports:
   - 8183:80
  environment:
   MYSQL_USERNAME: illya
   MYSQL_ROOT_PASSWORD: 
